# Global config
spring:
  docker:
    compose:
      # We don't want to use docker compose in prod and test
      enabled: false
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  profiles:
    # Value comes from Maven profile (pom.xml)
    active: "@spring.profiles.active@"
  flyway:
    locations: classpath:db/migrations/{vendor}/
    enabled: true

springdoc:
  swagger-ui:
    path: /
    tags-sorter: alpha
  show-actuator: true
management:
  info:
    env:
      enabled: true
  endpoint:
    health:
      show-components: always
    shutdown:
      enabled: true # For debugging
  endpoints:
    web:
      exposure:
        include: health, info, metrics, shutdown

server:
  port: 8080
  servlet:
    context-path: "/authentication"

# --- Custom keys ---

app:
  docs-api-url: "${DOCS_API_URL:(no value)}"

info:
  name: "@project.name@"
  description: "@project.description@"
  version: "@project.version@"

jwt:
  token:
    key:
      private: "${JWT_PRIVATE_KEY:}"
